import { useState } from 'react';


import Head from 'next/head';

export default function Home() {
  const [employeeId, setEmployeeId] = useState('');
  const handleInputChange = (event) => {
    setEmployeeId(event.target.value);
  };

  const handleClick = (event) => {
    event.preventDefault(); // Prevent the default form submission behavior

    if (!employeeId) {
      console.log('Please provide an input to continue');
      return;
    }

    // Create the request body
    const requestBody = {
      employee_id: employeeId,
    };

    // Send the HTTP POST request to save the employeeId
    fetch('/api/endpoint', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify(requestBody),
    })
      .then((response) => {
        if (response.ok) {
          window.location.href = '/employee_logs'; // Redirect to the specified page
        } else {
          throw new Error('An error occurred while saving the form data');
        }
      })
      .catch((error) => {
        console.error('Error saving form data:', error);
      });
  };

  return (
    <>
         <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon_chimp.ico" />
      </Head>
      <div>
  
        <h1 className='home_page'>Home page </h1>
        <div className="user_container_main">
        <div className="user_container">
        <form>
          <label htmlFor="employee_id">Enter Employee ID</label>
          <br />
          <input
            type="text"
            id="employee_id"
            value={employeeId}
            onChange={handleInputChange}
          />
          <br />
          <button onClick={handleClick}>Submit</button>
          
        </form>
        </div>
        </div>
      </div>
    </>
  );
}
